spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books
    username: application
    password: 123456@application
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#  security:
#    user:
#      name: application
#      password: password