spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books
    username: application
    password: 123456@application
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      log-level: DEBUG
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /book-store.html
