version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'books'
      MYSQL_USER: 'application'
      MYSQL_PASSWORD: '123456@application'
      MYSQL_ROOT_PASSWORD: 'root@admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/bootcamp/mysql
volumes:
  database:
